# Configuraciones de arranque generales de mi app de spring
# Siempre se cargan
spring.datasource.url=jdbc:mysql://localhost:3307/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=password
# driver class name es opcional (ya viene configurado)
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Para visualizar y debuggear las querys
spring.jpa.show-sql=true

# Definir el comportamiento de la estructura de bdd
spring.jpa.hibernate.ddl-auto=create
# es opcinal y se los recomiendo cuando su app no reconozca el conector
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#server.port=0 para manejar el choque de puertos